services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # api to send data
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: andhika
      MINIO_ROOT_PASSWORD: andhika123
    command: server /data --console-address ":9001"

volumes:
  minio_data: